version: '3'
services:
  zookeeper:
    image: zookeeper:latest
    #image: wurstmeister/zookeeper
    #environment:
    #  ZOO_MY_ID: 1
    ports:
      - "2181:2181"
  kafka1:
    image: wurstmeister/kafka
    #image: test123
    #build: .
    depends_on:
      - zookeeper
    ports:
      - "19091:9092"
    environment:
      KAFKA_BROKER_ID: 101
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_HOST}
      KAFKA_ADVERTISED_PORT: 19091
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_CREATE_TOPICS: "logging:3:2"
    dns: 8.8.4.4
     #Ok, looks like the broker ids may persist for a while, so make sure we remove them before starting
    command: bash -c '/opt/kafka/bin/zookeeper-shell.sh zookeeper:2181 rmr /brokers/ids/101 && start-kafka.sh'
    #volumes:
    #  - /var/run/docker.sock:/var/run/docker.sock
  kafka2:
    image: wurstmeister/kafka
    #image: test123
    #build: .
    depends_on:
      - zookeeper
    ports:
      - "19092:9092"
    environment:
      KAFKA_BROKER_ID: 102
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_HOST}
      KAFKA_ADVERTISED_PORT: 19092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_CREATE_TOPICS: "logging:3:2"
    dns: 8.8.4.4
     #Ok, looks like the broker ids may persist for a while, so make sure we remove them before starting
    command: bash -c '/opt/kafka/bin/zookeeper-shell.sh zookeeper:2181 rmr /brokers/ids/102 && start-kafka.sh'
    #volumes:
    #  - /var/run/docker.sock:/var/run/docker.sock
  kafka3:
    image: wurstmeister/kafka
    #image: test123
    #build: .
    depends_on:
      - zookeeper
    ports:
      - "19093:9092"
    environment:
      KAFKA_BROKER_ID: 103
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_HOST}
      KAFKA_ADVERTISED_PORT: 19093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_CREATE_TOPICS: "logging:3:2"
    dns: 8.8.4.4
     #Ok, looks like the broker ids may persist for a while, so make sure we remove them before starting
    command: bash -c '/opt/kafka/bin/zookeeper-shell.sh zookeeper:2181 rmr /brokers/ids/103 && start-kafka.sh'
    #volumes:
    #  - /var/run/docker.sock:/var/run/docker.sock
